module.exports = [ {
    id: 1,
    productName: 'Golden Flower Pearl Earrings',
    description: 'Bright gold earrings, handmade item, flower studs',
    available: true,
    quantityAvailable: 100,
    features: [ 'Sunshine yellow', 'Fresh real pearl', 'High Quality'],
    image: 'golden_flower_pearl_earrings.jpg',
    maxQuantity: 5,
    minQuantity: 1,
    price: 19.99,
   
}, 
{
    id: 2,
    productName: 'Jade Cross Bead Necklace',
    description: 'Beautiful real jade cross necklace',
    available: true,
    quantityAvailable: 40,
    features: [ 'Fresh River Pearls', 'Real Jade Beads', 'Real Jade Cross'],
    image: 'jade_cross_bead_necklace.jpg',
    maxQuantity: 10,
    minQuantity: 1,
    price: 39.99,
  
},
{
    id: 3,
    productName: 'Lavender Floral Earrings',
    description: 'Rose pedal flower ruffled tassel earrings',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Sterling Silver', 'Gold Cap', 'Brass'],
    image: 'lavender_floral_earrings.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 5.99,
},
{
    id: 4,
    productName: 'Marble Blue Crystal Necklace',
    description: '1pc stone pendant. Cloud Quartzite blue necklace',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Sterling silver', 'Simple accent jewelry'],
    image: 'marble_blue_necklace.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 18.99,
},
{
    id: 5,
    productName: 'Midnight Bead Necklace',
    description: 'Black pearl necklace',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Fresh pearl'],
    image: 'midnight_bead_necklace.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 34.99,
},
{
    id: 6,
    productName: 'Orange Burst Bead Necklace',
    description: 'Warm, shell pearl necklace',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Shell Pearls'],
    image: 'orange_burst_bead_necklace.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 49.99,
},
{
    id: 7,
    productName: 'Strawberry Milkshake Necklace',
    description: 'Sweet, multi color pearl necklace',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Fresh Pearls'],
    image: 'strawberry_milkshake_necklace.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 49.99,
},
{
    id: 8,
    productName: 'Sun Kiss Flower Pearl Necklace',
    description: 'Stunning shell and fresh pearl necklace',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Shell Pearls', 'Fresh Pearl Flowers'],
    image: 'sun_kiss_flower_pearl_necklace.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 69.99,
},
{
    id: 9,
    productName: 'White Flower Necklace',
    description: 'Shell, white flower necklace',
    available: false,
    quantityAvailable: 0,
    features: [ 'Handmade', 'Shell', 'Sterling Silver'],
    image: 'white_flower_necklace.jpg',
    maxQuantity: 0,
    minQuantity: 0,
    price: 14.99,
} ]